"""SQLAlchemy models for the Helpdesk module (docs/helpdesk.md).

Ticket system replacing OTRS: tickets are created from a web form or pulled
from a support mailbox, processed by support agents, threaded with the
requester over both the portal and email, and eventually archived.

The archive table (:class:`HelpdeskTicketArchive`) is not mapped as a model
here — it is partitioned and accessed through raw SQL in the archive service.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    BigInteger,
    Boolean,
    Computed,
    DateTime,
    ForeignKey,
    Identity,
    Index,
    Integer,
    SmallInteger,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy import text as sql_text
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.user import User


class HelpdeskTicket(Base):
    """A support request: ``new → open → pending → closed``.

    ``number`` is the human-readable ``TKT-{number}`` identifier, generated by
    PostgreSQL as an IDENTITY column (not a regular SERIAL) so it cannot be
    overwritten by INSERTs.
    """

    __tablename__ = "helpdesk_tickets"
    __table_args__ = (
        Index("ix_helpdesk_tickets_status", "status"),
        Index(
            "ix_helpdesk_tickets_assignee",
            "assignee_user_id",
            postgresql_where=sql_text("assignee_user_id IS NOT NULL"),
        ),
        Index(
            "ix_helpdesk_tickets_requester",
            "requester_user_id",
            postgresql_where=sql_text("requester_user_id IS NOT NULL"),
        ),
        Index("ix_helpdesk_tickets_email", sql_text("LOWER(requester_email)")),
        Index("ix_helpdesk_tickets_last_activity", "last_activity_at", postgresql_using="btree"),
        Index(
            "ix_helpdesk_tickets_open_list",
            "status",
            "last_activity_at",
            postgresql_where=sql_text("status IN ('new','open','pending')"),
            postgresql_using="btree",
        ),
        Index(
            "ix_helpdesk_tickets_ref_archive",
            "references_archived_ticket_number",
            postgresql_where=sql_text("references_archived_ticket_number IS NOT NULL"),
        ),
        # Полнотекстовый поиск (миграция 078): tsvector over (subject + description).
        # Запрос — websearch_to_tsquery('russian_hunspell', q) @@ search_tsvector.
        Index("idx_helpdesk_tickets_fts", "search_tsvector", postgresql_using="gin"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=sql_text("gen_random_uuid()")
    )
    number: Mapped[int] = mapped_column(
        BigInteger,
        Identity(always=True),
        unique=True,
        nullable=False,
    )
    subject: Mapped[str] = mapped_column(String(500), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    description_html: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default=sql_text("'new'")
    )
    source: Mapped[str] = mapped_column(String(20), nullable=False)

    requester_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    requester_email: Mapped[str] = mapped_column(String(320), nullable=False)
    requester_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    assignee_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    assigned_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    closed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    last_activity_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    references_archived_ticket_number: Mapped[int | None] = mapped_column(BigInteger, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sql_text("NOW()"),
        onupdate=lambda: datetime.now(UTC),
    )
    # Полнотекстовый поиск (миграция 078): generated STORED tsvector over
    # (subject + description). Запись не нужна — вычисляется БД автоматически.
    search_tsvector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(
            "to_tsvector('russian_hunspell',"
            " coalesce(subject, '') || ' ' || coalesce(description, ''))",
            persisted=True,
        ),
        nullable=True,
    )

    requester_user: Mapped[User | None] = relationship(
        "User", foreign_keys=[requester_user_id], lazy="select"
    )
    assignee: Mapped[User | None] = relationship(
        "User", foreign_keys=[assignee_user_id], lazy="select"
    )
    closed_by: Mapped[User | None] = relationship(
        "User", foreign_keys=[closed_by_user_id], lazy="select"
    )
    messages: Mapped[list[HelpdeskMessage]] = relationship(
        "HelpdeskMessage",
        back_populates="ticket",
        cascade="all, delete-orphan",
        order_by="HelpdeskMessage.created_at",
        lazy="selectin",
    )

    @property
    def ticket_number(self) -> str:
        """Human-readable identifier, e.g. ``TKT-123``."""
        return f"TKT-{self.number}"


class HelpdeskMessage(Base):
    """A single message in a ticket thread — public (visible to the requester)
    or internal (agent-only note), inbound (from the requester) or outbound
    (from an agent)."""

    __tablename__ = "helpdesk_messages"
    __table_args__ = (
        Index(
            "uq_helpdesk_messages_email_msg_id",
            "email_message_id",
            unique=True,
            postgresql_where=sql_text("email_message_id IS NOT NULL"),
        ),
        Index("ix_helpdesk_messages_ticket", "ticket_id", "created_at"),
        # Полнотекстовый поиск по телам ответов (миграция 078).
        Index("idx_helpdesk_messages_fts", "body_tsvector", postgresql_using="gin"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=sql_text("gen_random_uuid()")
    )
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("helpdesk_tickets.id", ondelete="CASCADE"),
        nullable=False,
    )
    author_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    author_email: Mapped[str] = mapped_column(String(320), nullable=False)
    author_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)
    visibility: Mapped[str] = mapped_column(
        String(10), nullable=False, server_default=sql_text("'public'")
    )
    body_text: Mapped[str] = mapped_column(Text, nullable=False)
    body_html: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Полнотекстовый поиск по телу ответа (миграция 078): generated STORED
    # tsvector over body_text. Только plain — HTML-теги засоряли бы вектор.
    body_tsvector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('russian_hunspell', coalesce(body_text, ''))", persisted=True),
        nullable=True,
    )
    source: Mapped[str] = mapped_column(String(20), nullable=False)
    email_message_id: Mapped[str | None] = mapped_column(String(998), nullable=True)
    in_reply_to: Mapped[str | None] = mapped_column(String(998), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )

    ticket: Mapped[HelpdeskTicket] = relationship(
        "HelpdeskTicket", back_populates="messages", lazy="select"
    )
    author: Mapped[User | None] = relationship("User", foreign_keys=[author_user_id], lazy="select")
    attachments: Mapped[list[HelpdeskAttachment]] = relationship(
        "HelpdeskAttachment",
        back_populates="message",
        cascade="all, delete-orphan",
        lazy="selectin",
    )


class HelpdeskAttachment(Base):
    """File attached to a ticket message. Stored **locally** in
    ``/data/helpdesk/TKT-{number}/{filename}`` (по образцу feedback); only
    metadata lives in the DB. Nextcloud is NOT used for helpdesk attachments."""

    __tablename__ = "helpdesk_attachments"
    __table_args__ = (
        Index("ix_helpdesk_attachments_ticket", "ticket_id"),
        Index("ix_helpdesk_attachments_message", "message_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=sql_text("gen_random_uuid()")
    )
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("helpdesk_tickets.id", ondelete="CASCADE"),
        nullable=False,
    )
    message_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("helpdesk_messages.id", ondelete="CASCADE"),
        nullable=True,
    )
    filename: Mapped[str] = mapped_column(String(500), nullable=False)
    original_name: Mapped[str] = mapped_column(String(500), nullable=False)
    content_type: Mapped[str] = mapped_column(String(255), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    # Inline-картинки в теле сообщения: ``is_inline=True`` + ``content_id`` (без
    # угловых скобок) → в исходящем письме встраиваются как ``cid:``-attach
    # (``multipart/related``), а в ленте портала рендерятся по относительному
    # ``/api/v1/helpdesk/attachments/{id}``. Обычные вложения (``is_inline=False``,
    # ``content_id IS NULL``) уходят как ``Content-Disposition: attachment``.
    is_inline: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=sql_text("false")
    )
    content_id: Mapped[str | None] = mapped_column(String(320), nullable=True)
    uploaded_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )

    message: Mapped[HelpdeskMessage | None] = relationship(
        "HelpdeskMessage", back_populates="attachments", lazy="select"
    )
    uploaded_by: Mapped[User | None] = relationship(
        "User", foreign_keys=[uploaded_by_user_id], lazy="select"
    )


class HelpdeskDraftAttachment(Base):
    """Temporary inline-image uploaded through the ticket **creation** form,
    before the ticket exists (chicken-and-egg: ``POST /tickets/{id}/inline-media``
    needs a ``ticket_id``).

    On ``create_ticket``, :func:`backfill_draft_images` moves the file to the
    ticket's permanent ``TKT-{number}/inline/`` folder, rewrites ``<img src>``
    to a stable inline-media URL, and deletes this row — all in the ticket
    creation transaction. Rows whose draft was never backfilled (user abandoned
    the form) are purged by the ``cleanup_expired_drafts`` cron after
    ``HELPDESK_DRAFT_TTL_HOURS``.

    Only metadata lives here; the bytes are on disk at
    ``/data/helpdesk/drafts/usr-{user_id}/{filename}``. No relationships —
    drafts are ephemeral, the FK to ``users`` is solely for ``ON DELETE CASCADE``
    cleanup on account deletion.
    """

    __tablename__ = "helpdesk_draft_attachments"
    __table_args__ = (
        Index("ix_helpdesk_draft_attachments_user", "uploaded_by_user_id"),
        Index("ix_helpdesk_draft_attachments_created", "created_at"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=sql_text("gen_random_uuid()")
    )
    uploaded_by_user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    filename: Mapped[str] = mapped_column(String(500), nullable=False)
    original_name: Mapped[str] = mapped_column(String(500), nullable=False)
    content_type: Mapped[str] = mapped_column(String(255), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )


class HelpdeskAgent(Base):
    """A support agent — an operational unit, distinct from portal roles
    (``users.role``). Membership in this table is the single source of truth for
    agent privileges (checked per-request by ``require_helpdesk_agent``)."""

    __tablename__ = "helpdesk_agents"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        primary_key=True,
    )
    added_by: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    added_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    notify_new: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=sql_text("TRUE"), default=True
    )

    user: Mapped[User] = relationship("User", foreign_keys=[user_id], lazy="select")
    adder: Mapped[User | None] = relationship("User", foreign_keys=[added_by], lazy="select")


class HelpdeskEmailLog(Base):
    """Idempotency log for IMAP ingress — keyed by the incoming ``Message-ID``
    (or synthetic id) so that re-downloading the same message never creates a
    duplicate ticket/message."""

    __tablename__ = "helpdesk_email_log"
    __table_args__ = (Index("ix_helpdesk_email_log_received", "received_at"),)

    message_id: Mapped[str] = mapped_column(String(998), primary_key=True)
    ticket_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("helpdesk_tickets.id", ondelete="SET NULL"),
        nullable=True,
    )
    message_db_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("helpdesk_messages.id", ondelete="SET NULL"),
        nullable=True,
    )
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)


class HelpdeskMailboxSettings(Base):
    """Singleton row (``id = 1``) holding the IMAP/SMTP configuration of the
    support mailbox. The IMAP password is stored encrypted at rest
    (``imap_password_enc``); the plaintext is never returned by the API."""

    __tablename__ = "helpdesk_mailbox_settings"

    id: Mapped[int] = mapped_column(SmallInteger, primary_key=True, default=1)
    imap_host: Mapped[str] = mapped_column(String(255), nullable=False)
    imap_port: Mapped[int] = mapped_column(Integer, nullable=False, server_default=sql_text("993"))
    imap_username: Mapped[str] = mapped_column(String(255), nullable=False)
    imap_password_enc: Mapped[str] = mapped_column(Text, nullable=False)
    imap_use_ssl: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=sql_text("TRUE"), default=True
    )
    imap_folder: Mapped[str] = mapped_column(
        String(255), nullable=False, server_default=sql_text("'INBOX'"), default="INBOX"
    )
    poll_interval_seconds: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=sql_text("60"), default=60
    )
    delete_after_fetch: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=sql_text("FALSE"), default=False
    )
    support_address: Mapped[str] = mapped_column(String(320), nullable=False)
    support_reply_to: Mapped[str | None] = mapped_column(String(320), nullable=True)
    updated_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sql_text("NOW()"),
        onupdate=lambda: datetime.now(UTC),
    )

    updated_by: Mapped[User | None] = relationship(
        "User", foreign_keys=[updated_by_user_id], lazy="select"
    )


class HelpdeskTicketArchive(Base):
    """Read-only archive of closed tickets (partitioned by ``closed_at``).
    The full ticket with its messages and attachment metadata is captured in
    ``payload`` as JSONB; the live row is removed from :class:`HelpdeskTicket`
    after archival. Accessed in practice through raw SQL in the archive
    service; the model exists for metadata introspection and consistent typing."""

    __tablename__ = "helpdesk_tickets_archive"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    number: Mapped[int] = mapped_column(BigInteger, nullable=False)
    subject: Mapped[str] = mapped_column(String(500), nullable=False)
    requester_email: Mapped[str] = mapped_column(String(320), nullable=False)
    requester_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    assignee_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    opened_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    closed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), primary_key=True)
    closed_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False)
    archived_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )


class HelpdeskDigestSettings(Base):
    """Singleton row (``id = 1``) holding the daily digest email schedule.

    The digest is sent once per day (cron-driven worker
    ``send_helpdesk_digest``) to every active helpdesk agent: their assigned
    ``open``/``pending`` tickets plus all ``unassigned`` tickets. Unlike
    :class:`HelpdeskMailboxSettings`, the row is seeded by the migration (no
    NOT NULL column without a DEFAULT), so it always exists and ``enabled``
    can be toggled without a separate "configured" state.
    """

    __tablename__ = "helpdesk_digest_settings"

    id: Mapped[int] = mapped_column(SmallInteger, primary_key=True, default=1)
    enabled: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=sql_text("TRUE"), default=True
    )
    digest_hour: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, server_default=sql_text("8"), default=8
    )
    digest_minute: Mapped[int] = mapped_column(
        SmallInteger, nullable=False, server_default=sql_text("0"), default=0
    )
    digest_schedule: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default=sql_text("'weekdays'"), default="weekdays"
    )
    updated_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sql_text("NOW()"),
        onupdate=lambda: datetime.now(UTC),
    )

    updated_by: Mapped[User | None] = relationship(
        "User", foreign_keys=[updated_by_user_id], lazy="select"
    )


class HelpdeskMaxBotSettings(Base):
    """Singleton row (``id = 1``) holding the MAX-messenger bot configuration
    for helpdesk notifications (new tickets → common support chat).

    ``bot_token_enc`` is encrypted at rest through ``app.core.secret_crypto``
    (Fernet derived from ``SECRET_KEY``); the plaintext is never returned by
    the API (write-only, like ``HelpdeskMailboxSettings.imap_password_enc``).

    By design (mirrors :class:`HelpdeskDigestSettings`, migration 076): every
    column is either nullable or has a DEFAULT, the row is seeded by migration
    081 with ``enabled=False``, and the admin flips the switch in the Helpdesk
    tab after entering the token and chat_id. No separate ``configured`` state
    is tracked — ``enabled=False`` until both token and chat_id are provided.
    """

    __tablename__ = "helpdesk_max_bot_settings"

    id: Mapped[int] = mapped_column(SmallInteger, primary_key=True, default=1)
    enabled: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=sql_text("FALSE"), default=False
    )
    bot_token_enc: Mapped[str | None] = mapped_column(Text, nullable=True)
    chat_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    updated_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sql_text("NOW()"),
        onupdate=lambda: datetime.now(UTC),
    )

    updated_by: Mapped[User | None] = relationship(
        "User", foreign_keys=[updated_by_user_id], lazy="select"
    )


class MessengerOutbox(Base):
    """Transactional outbox for outbound messenger notifications (mirror of
    :class:`email_outbox` for non-email channels).

    ``provider`` reserves room for future channels (Telegram/Slack); only
    ``'max'`` is implemented. CRUD is done through raw SQL in
    :mod:`app.services.messenger_outbox` (FOR UPDATE SKIP LOCKED, retry/backoff);
    this ORM mapping exists only for metadata introspection and typing.

    ``payload`` (JSONB) stores provider-specific content: for MAX it carries
    ``attachments`` (inline-keyboard with a "open on portal" URL button) and
    any extra metadata. ``text`` is the message body itself.
    """

    __tablename__ = "messenger_outbox"
    __table_args__ = (
        Index(
            "ix_messenger_outbox_pending",
            "next_attempt_at",
            postgresql_where=sql_text("status = 'PENDING'"),
        ),
        Index(
            "ix_messenger_outbox_stale",
            "updated_at",
            postgresql_where=sql_text("status = 'SENDING'"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=sql_text("gen_random_uuid()")
    )
    provider: Mapped[str] = mapped_column(String(32), nullable=False)
    chat_id: Mapped[str] = mapped_column(String(64), nullable=False)
    text: Mapped[str] = mapped_column(Text, nullable=False)
    payload: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=sql_text("'{}'::jsonb")
    )
    status: Mapped[str] = mapped_column(
        String(16), nullable=False, server_default=sql_text("'PENDING'")
    )
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default=sql_text("0"))
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, server_default=sql_text("6"))
    next_attempt_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    last_error_type: Mapped[str | None] = mapped_column(String(128), nullable=True)
    last_error_class: Mapped[str | None] = mapped_column(String(16), nullable=True)
    last_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    related_resource_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    related_resource_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    created_by_user_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=sql_text("NOW()"),
        onupdate=lambda: datetime.now(UTC),
    )


class HelpdeskTicketRead(Base):
    """Per-agent read-state marker: «когда этот агент последний раз видел тикет».

    Подсветка непрочитанных заявок в инбоксе агента (миграция 080). Тикет
    «непрочитан» для агента, если существует публичное входящее сообщение
    (``direction='inbound'``, ``visibility='public'`` — ответ заявителя) с
    ``created_at > COALESCE(last_seen_at, '-infinity')``. Ответы других агентов
    и свои собственные НЕ считаются (агент и так их видел — он их писал);
    internal-заметки НЕ считаются (это служебная активность).

    Одна строка на пару ``ticket_id`` × ``user_id`` (UNIQUE-индекс), UPSERT
    через ``ON CONFLICT`` при открытии карточки агента. ``ON DELETE CASCADE``
    на обеих FK → чистится автоматически при архивации/удалении тикета или
    аккаунта, cleanup-cron не нужен.

    По образцу ``news_likes`` / ``kb_article_feedback`` (marker-таблица с
    композитным UNIQUE); архитектурно ближе к Zammad/FreeScout
    (``conversation_user`` pivot с ``last_seen_at``), чем к OTRS (per-article
    ``ticket_flag`` — избыточно для наших объёмов).
    """

    __tablename__ = "helpdesk_ticket_reads"
    __table_args__ = (
        UniqueConstraint("ticket_id", "user_id", name="uq_helpdesk_ticket_reads_ticket_user"),
        Index("ix_helpdesk_ticket_reads_user", "user_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=sql_text("gen_random_uuid()")
    )
    ticket_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("helpdesk_tickets.id", ondelete="CASCADE"),
        nullable=False,
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sql_text("NOW()")
    )
