"""TST-05: iCal DTSTART/DTEND must be serialized in UTC (no TZID).

Outlook misinterprets the historical VTIMEZONE generated by
``icalendar.Timezone.from_tzinfo()`` for Europe/Moscow (Medvedev's 2011
+0400 transition is the last STANDARD rule; the 2014 fallback to +0300
lives only inside an RDATE of another component). To stay safe across
all clients we emit times in UTC and let the client convert.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from types import SimpleNamespace

import pytest

icalendar = pytest.importorskip("icalendar")
Calendar = icalendar.Calendar


def _make_room(tz: str = "Europe/Moscow"):
    return SimpleNamespace(
        id=uuid.uuid4(),
        name="Room",
        timezone=tz,
        link=None,
        email=None,
    )


def _make_booking(room):
    return SimpleNamespace(
        id=uuid.uuid4(),
        title="x",
        organizer_name="O",
        description=None,
        start_time=datetime(2030, 1, 15, 7, 0, tzinfo=UTC),
        end_time=datetime(2030, 1, 15, 8, 0, tzinfo=UTC),
        invited_users=[],
        series_id=None,
        recurrence_rule=None,
        update_count=0,
        rooms=[SimpleNamespace(room=room)],
    )


def _get_event_tzids(data: bytes) -> set[str]:
    cal = Calendar.from_ical(data)
    out: set[str] = set()
    for event in cal.walk("VEVENT"):
        for prop in ("DTSTART", "DTEND"):
            val = event.get(prop)
            if val is None:
                continue
            tz = val.params.get("TZID") if hasattr(val, "params") else None
            if tz:
                out.add(str(tz))
    return out


@pytest.mark.parametrize("tz", ["Europe/Moscow", "Asia/Novosibirsk"])
def test_dtstart_dtend_serialized_as_utc(tz: str):
    from app.services.meetings.ical_builder import build_ical

    room = _make_room(tz)
    booking = _make_booking(room)
    data = build_ical(
        booking,
        "REQUEST",
        "portal.local",
        "noreply@portal.local",
        portal_tz=tz,
    )

    assert _get_event_tzids(data) == set(), "DTSTART/DTEND must not carry TZID"
    assert b"DTSTART:20300115T070000Z" in data
    assert b"DTEND:20300115T080000Z" in data
