export const queryKeys = {
  admin: {
    all: ['admin'] as const,
    users: (params?: Record<string, unknown>) => ['admin', 'users', params ?? {}] as const,
    audit: (params?: Record<string, unknown>) => ['admin', 'audit', params ?? {}] as const,
    auditEventTypes: () => ['admin', 'audit-event-types'] as const,
    auditQueue: () => ['admin', 'audit-queue'] as const,
    analyticsDashboard: () => ['admin', 'analytics', 'dashboard'] as const,
    analyticsTopArticles: () => ['admin', 'analytics', 'top-articles'] as const,
    analyticsTopNews: () => ['admin', 'analytics', 'top-news'] as const,
    analyticsTopFiles: () => ['admin', 'analytics', 'top-files'] as const,
    analyticsDepartments: () => ['admin', 'analytics', 'departments'] as const,
    emailSettings: () => ['admin', 'email-settings'] as const,
    systemSettings: () => ['admin', 'system-settings'] as const,
    tlsStatus: () => ['admin', 'tls-status'] as const,
    keycloakSettings: () => ['admin', 'keycloak-settings'] as const,
    keycloakSyncStatus: () => ['admin', 'keycloak-sync-status'] as const,
    modules: () => ['admin', 'modules-config'] as const,
    userAttributes: () => ['admin', 'user-attributes'] as const,
    discoverAttributes: () => ['admin', 'discover-attributes'] as const,
    links: () => ['admin', 'links'] as const,
  },
  photos: {
    all: ['photos'] as const,
    myShares: () => ['photos', 'my-shares'] as const,
    recent: (limit?: number) => ['photos', 'recent', limit ?? 8] as const,
    folderTree: () => ['photos', 'folder-tree'] as const,
    folder: (id: string) => ['photos', 'folder', id] as const,
  },
  news: {
    all: ['news'] as const,
    list: (params?: Record<string, unknown>) => ['news', 'list', params ?? {}] as const,
    detail: (id: string) => ['news', 'detail', id] as const,
    gallery: (id: string) => ['news', 'gallery', id] as const,
    attachments: (id: string) => ['news', 'attachments', id] as const,
    categories: () => ['news', 'categories'] as const,
    limits: () => ['news', 'limits'] as const,
  },
  kb: {
    all: ['kb'] as const,
    articles: (params?: Record<string, unknown>) => ['kb', 'articles', params ?? {}] as const,
    article: (id: string) => ['kb', 'article', id] as const,
    tags: () => ['kb', 'tags'] as const,
    sections: () => ['kb', 'sections'] as const,
    comments: (articleId: string) => ['kb', 'comments', articleId] as const,
    versions: (articleId: string) => ['kb', 'versions', articleId] as const,
  },
  users: {
    all: ['users'] as const,
    list: (params?: Record<string, unknown>) => ['users', 'list', params ?? {}] as const,
    departments: (ordered = false) => ['users', 'departments', ordered] as const,
    offices: () => ['users', 'offices'] as const,
    detail: (id: string) => ['users', 'detail', id] as const,
    attributeSchema: () => ['users', 'attribute-schema'] as const,
    keycloakGroups: (id: string) => ['users', 'keycloak-groups', id] as const,
  },
  links: {
    all: ['links'] as const,
    list: (params?: Record<string, unknown>) => ['links', 'list', params ?? {}] as const,
    bookmarks: () => ['links', 'bookmarks'] as const,
  },
  notifications: {
    all: ['notifications'] as const,
    list: (params?: Record<string, unknown>) => ['notifications', 'list', params ?? {}] as const,
    unreadCount: () => ['notifications', 'unread-count'] as const,
  },
  modules: {
    all: ['modules'] as const,
    settings: () => ['modules', 'settings'] as const,
  },
  files: {
    all: ['files'] as const,
    tree: () => ['files', 'tree'] as const,
    folder: (id: string) => ['files', 'folder', id] as const,
  },
  portal: {
    staffSettings: () => ['portal', 'staff-settings'] as const,
  },
} as const
