#!/usr/bin/env bash
# Phase-5 diff-coverage: compare current PR coverage.xml against main baseline.
#
# Expects:
#   backend/coverage.xml         current run (generated by pytest --cov-report=xml)
#   .ci-baseline/coverage.xml    main-branch baseline (refreshed by CI on push to main)
#
# Usage:
#   ./scripts/diff-cover.sh                        # default thresholds (80% diff)
#   THRESHOLD=70 ./scripts/diff-cover.sh
#   ./scripts/diff-cover.sh --compare-branch=origin/main
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

COV="${COV:-backend/coverage.xml}"
THRESHOLD="${THRESHOLD:-80}"
BRANCH="${COMPARE_BRANCH:-origin/main}"

if ! command -v diff-cover >/dev/null 2>&1; then
  echo "diff-cover not installed; install via: pip install diff-cover" >&2
  exit 2
fi

if [[ ! -f "$COV" ]]; then
  echo "coverage report not found at $COV" >&2
  echo "run: cd backend && pytest --cov=app --cov-report=xml" >&2
  exit 2
fi

diff-cover "$COV" \
  --compare-branch "$BRANCH" \
  --fail-under "$THRESHOLD" \
  "$@"
